baseURL = 'https://jostgrant.github.io/gdmod/'
languageCode = 'en-us'
title = 'mod - Godot Sandbox / Playground'
publishDir = '../docs'

[params]
  description = "A Garry's Mod styled sandbox and playground built in Godot"
  author = "Joshua Steven Grant (ie: Jost Grant)"
  keywords = ["godot", "sandbox", "garry's mod", "playground", "game"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Features"
    url = "/#features"
    weight = 20
  [[menu.main]]
    name = "Download"
    url = "/#download"
    weight = 30
  [[menu.main]]
    name = "Documentation"
    url = "/docs"
    weight = 40